@echo off
cd /d "%~dp0"
if not exist .venv (
    echo Virtual environment (.venv) not found! Creating one...
    python -m venv .venv
)
echo Activating virtual environment...
call .venv\Scripts\activate.bat
echo Installing Python dependencies...
pip install -r requirements.txt
echo Downloading spaCy en_core_web_sm model...
python -m spacy download en_core_web_sm
echo Starting FastAPI NLP service on port 8000...
uvicorn main:app --host 0.0.0.0 --port 8000 --reload

